install.packages("nycflights13")
library(nycflights13)
data_a <- flights
library(dplyr)
data <-sample_n(data_a,30)

df1 <- data %>% group_by(carrier) %>% summarise(mean_arr_delay = mean(arr_delay, na.rm=TRUE)) %>%   filter(mean_arr_delay >= 30) %>% arrange(mean_arr_delay)
df2 <- data %>% group_by(carrier,flight) %>% summarise(mean_arr_delay = mean(arr_delay, na.rm=TRUE)) %>%   filter(mean_arr_delay >= 30) %>% arrange(mean_arr_delay)
df3<- data %>% group_by(carrier,flight,tailnum) %>% summarise(mean_arr_delay = mean(arr_delay, na.rm=TRUE)) %>%  filter(mean_arr_delay >= 30) %>% arrange(mean_arr_delay)

df4d <- data %>% group_by(carrier,flight) %>%  summarise(mean_arr_delay = mean(arr_delay, na.rm=TRUE), mean_dep_delay = mean(dep_delay, na.rm=TRUE)) %>%   filter(mean_arr_delay > 30 & mean_dep_delay > 25) 
View(data)
summary(data)
names(data)
summary(data$distance)
mean(data$distance)
with(data, mean(distance))
median(data$distance)
var(data$distance) 
sd(data$distance) 
max(data$distance) 
min(data$distance) 
range(data$distance) 
quantile(data$distance)
quantile(data$distance, c(.3, .6, .9))
which.max(data$distance) 
which.min(data$distance)
